// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Vite
// plugin that tells the Electron app where to look for the Vite-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_VITE_DEV_SERVER_URL: string;
declare const MAIN_WINDOW_VITE_NAME: string;

// Preload types
interface ThemeModeContext {
  toggle: () => Promise<boolean>;
  dark: () => Promise<void>;
  light: () => Promise<void>;
  system: () => Promise<boolean>;
  current: () => Promise<"dark" | "light" | "system">;
}
interface ElectronWindow {
  minimize: () => Promise<void>;
  maximize: () => Promise<void>;
  close: () => Promise<void>;
}

interface DatabaseAPI {
  initialize: () => Promise<{ success: boolean; error?: string }>;
  users: {
    getAll: (search?: string) => Promise<{ success: boolean; data?: any[]; error?: string }>;
    getById: (id: number) => Promise<{ success: boolean; data?: any; error?: string }>;
    create: (userData: any) => Promise<{ success: boolean; data?: any; error?: string }>;
    update: (id: number, userData: any) => Promise<{ success: boolean; data?: any; error?: string }>;
    delete: (id: number) => Promise<{ success: boolean; data?: boolean; error?: string }>;
  };
  products: {
    getAll: (search?: string) => Promise<{ success: boolean; data?: any[]; error?: string }>;
    getById: (id: number) => Promise<{ success: boolean; data?: any; error?: string }>;
    create: (productData: any) => Promise<{ success: boolean; data?: any; error?: string }>;
    update: (id: number, productData: any) => Promise<{ success: boolean; data?: any; error?: string }>;
    delete: (id: number) => Promise<{ success: boolean; data?: boolean; error?: string }>;
    getByCategory: (category: string) => Promise<{ success: boolean; data?: any[]; error?: string }>;
  };
  orders: {
    getAll: () => Promise<{ success: boolean; data?: any[]; error?: string }>;
    getById: (id: number) => Promise<{ success: boolean; data?: any; error?: string }>;
    create: (orderData: any) => Promise<{ success: boolean; data?: any; error?: string }>;
    update: (id: number, orderData: any) => Promise<{ success: boolean; data?: any; error?: string }>;
    delete: (id: number) => Promise<{ success: boolean; data?: boolean; error?: string }>;
    getByUser: (userId: number) => Promise<{ success: boolean; data?: any[]; error?: string }>;
  };
}

declare interface Window {
  themeMode: ThemeModeContext;
  electronWindow: ElectronWindow;
  database: DatabaseAPI;
}
